apiVersion: apps/v1
kind: Deployment
metadata:
  name: rair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rair
  template:
    metadata:
      labels:
        app: rair
    spec:
      containers:
      - image: okteto.dev/rair:latest
        name: rair
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.ietf.org"
        - name: Vless_UUID
          value: "4cc9c0f6-fab3-43d0-916c-2c54d182e0d0"
        - name: Vless_Path
          value: "/zloo"
        - name: Vmess_UUID
          value: "4cc9c0f6-fab3-43d0-916c-2c54d182e0d0"
        - name: Vmess_Path
          value: "/zmoo"
        - name: Share_Path
          value: "/share233"
