apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiy
  template:
    metadata:
      labels:
        app: xiy
    spec:
      containers:
      - image: okteto.dev/xiy:latest
        name: xiy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.ietf.org"
        - name: Vless_UUID
          value: "85f420c5-6b49-4a0e-84c5-dc99c0256b4a"
        - name: Vless_Path
          value: "/s3LV"
        - name: Vmess_UUID
          value: "85f420c5-6b49-4a0e-84c5-dc99c0256b4a"
        - name: Vmess_Path
          value: "/s4Lm"
        - name: Share_Path
          value: "/share233"
