apiVersion: apps/v1
kind: Deployment
metadata:
  name: yygs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yygs
  template:
    metadata:
      labels:
        app: yygs
    spec:
      containers:
      - image: okteto.dev/yygs:latest
        name: yygs
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.ietf.org"
        - name: Vless_UUID
          value: "fa66daeb-cad6-400a-9d0f-57f4d846787b"
        - name: Vless_Path
          value: "/4vsl"
        - name: Vmess_UUID
          value: "fa66daeb-cad6-400a-9d0f-57f4d846787b"
        - name: Vmess_Path
          value: "/4vsm"
        - name: Share_Path
          value: "/share233"
