apiVersion: apps/v1
kind: Deployment
metadata:
  name: yiwv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yiwv
  template:
    metadata:
      labels:
        app: yiwv
    spec:
      containers:
      - image: okteto.dev/yiwv:latest
        name: yiwv
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.ietf.org"
        - name: Vless_UUID
          value: "02174ad7-e63b-496d-86fd-f4453db8b0ea"
        - name: Vless_Path
          value: "/4lss"
        - name: Vmess_UUID
          value: "02174ad7-e63b-496d-86fd-f4453db8b0ea"
        - name: Vmess_Path
          value: "/ss3m"
        - name: Share_Path
          value: "/share233"
