apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  template:
    metadata:
      labels:
        app: bob
    spec:
      containers:
      - image: okteto.dev/bob:latest
        name: bob
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.ietf.org"
        - name: Vless_UUID
          value: "02174ad7-e63b-496d-86fd-f4453db8b0ea"
        - name: Vless_Path
          value: "/6lls"
        - name: Vmess_UUID
          value: "02174ad7-e63b-496d-86fd-f4453db8b0ea"
        - name: Vmess_Path
          value: "/smm6"
        - name: Share_Path
          value: "/share233"
