apiVersion: apps/v1
kind: Deployment
metadata:
  name: mokr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mokr
  template:
    metadata:
      labels:
        app: mokr
    spec:
      containers:
      - image: okteto.dev/mokr:latest
        name: mokr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "fb3930b5-56b6-403f-9f57-556cbfc2672a"
        - name: Vless_Path
          value: "/vvssl"
        - name: Vmess_UUID
          value: "fb3930b5-56b6-403f-9f57-556cbfc2672a"
        - name: Vmess_Path
          value: "/ssmll"
        - name: Share_Path
          value: "/share233"
