apiVersion: apps/v1
kind: Deployment
metadata:
  name: mokr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mokr
  template:
    metadata:
      labels:
        app: mokr
    spec:
      containers:
      - image: okteto.dev/mokr:latest
        name: mokr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d7fa252c-b0e1-4eb7-a461-99d1a5a82af1"
        - name: Vless_Path
          value: "/4lss"
        - name: Vmess_UUID
          value: "d7fa252c-b0e1-4eb7-a461-99d1a5a82af1"
        - name: Vmess_Path
          value: "/ss3m"
        - name: Share_Path
          value: "/share233"
