apiVersion: apps/v1
kind: Deployment
metadata:
  name: maia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maia
  template:
    metadata:
      labels:
        app: maia
    spec:
      containers:
      - image: okteto.dev/:latest
        name: maia
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.ietf.org"
        - name: Vless_UUID
          value: "fa66daeb-cad6-400a-9d0f-57f4d846787b"
        - name: Vless_Path
          value: "/s4l2"
        - name: Vmess_UUID
          value: "fa66daeb-cad6-400a-9d0f-57f4d846787b"
        - name: Vmess_Path
          value: "/s3l2"
        - name: Share_Path
          value: "/share233"
