apiVersion: v1
kind: Service
metadata:
  name: mokr
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "mokr"
    port: 8080
  selector:
    app: mokr
